### ISSUE TITLE
NLTK error when parsing sentences with unescaped parentheses.

### ISSUE THREAD

**Issue by norpadon** [yzhangcs/parser#115] opened 2022-12-28 04:55 UTC
```python3
sentence = 'This is a t(est)'
parser = Parser.load('crf-con-roberta-en')
parser.predict([sentence], lang='en', verbose=False)
```

crashes with a following error:
```
File /opt/homebrew/lib/python3.10/site-packages/nltk/tree/tree.py:731, in Tree._parse_error(cls, s, match, expecting)
    730 msg += '\n{}"{}"\n{}^'.format(" " * 16, s, " " * (17 + offset))
--> 731 raise ValueError(msg)

ValueError: Tree.read(): expected ')' but got 'end-of-string'
            at index 71.
                "..._ -RRB-)))"
                              ^
```

The same is true for `sentence = '(713)853-7041'`.

If I add a whitespace before `(` and `)`, everything works fine.

**Comment by yzhangcs** [comment] 2022-12-28 07:23
@norpadon Hi, the problem is caused because brackets are not totally handled after tokenization.
```py
>>> from supar.utils.tokenizer import Tokenizer
>>> t = Tokenizer()
>>> t('This is a t(est)')
['This', 'is', 'a', 't(', 'est', ')']
>>> t('This is a t (est)')
['This', 'is', 'a', 't', '(', 'est', ')']
```
This bug has been fixed by latest commits, referring to 
https://github.com/yzhangcs/parser/blob/ce34fc254e5a0757605c5be7db6a2cd089adc2f7/supar/utils/transform.py#L420-L458

**Closed** 2023-01-04 17:07 UTC
